DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS employers;
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table accounts
(
    id          bigint generated by default as identity,
    balance     float(53)    not null,
    currency    varchar(3)   not null check (currency in ('USD', 'EUR', 'UAH', 'CHF', 'GBP')),
    number      varchar(255) not null,
    customer_id bigint,
    primary key (id)
);

create table customers
(
    id    bigint generated by default as identity,
    age   integer      not null,
    email varchar(255) not null,
    name  varchar(255) not null,
    primary key (id)
);

create table employers
(
    id      bigint generated by default as identity,
    address varchar(255) not null,
    name    varchar(255) not null,
    primary key (id)
);

alter table if exists accounts
    add constraint FK_account_by_customer foreign key (customer_id) references customers